// PLAYWRIGHT_MODULE=/path/to/playwright node scripts/verify-loading.mjs
import { createRequire } from 'node:module';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const { chromium } = createRequire(import.meta.url)(process.env.PLAYWRIGHT_MODULE || 'playwright');
const browser = await chromium.launch({ channel: 'chrome' });
const directory = process.env.RENDER_ARTIFACT_DIR || '/tmp/house-loading';
fs.mkdirSync(directory, { recursive: true });
const base = process.env.RENDER_BASE_URL || 'http://localhost:3000';
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 960 }, reducedMotion: 'reduce' });
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('console', message => { if (message.type() === 'error' && /Cannot update|Maximum update/.test(message.text())) errors.push(message.text()); });
  let release;
  const assetsHeld = new Promise(resolve => { release = resolve; });
  await page.route(/\.(glb|jpe?g|png|webp)(\?.*)?$/, async route => { await assetsHeld; await route.continue(); });
  await page.goto(`${base}/?view=model&camera=room&zone=central-core&gardenQA=1`, { waitUntil: 'domcontentloaded' });
  await page.locator('.scene-loading-cover:not(.is-revealed)').waitFor({ timeout: 60000 });
  await page.screenshot({ path: `${directory}/initial.png` });
  assert.equal(await page.getByRole('button', { name: 'Explore the 2D plan' }).count(), 1);
  release();
  await page.locator('.scene-loading-cover.is-revealed').waitFor({ state: 'attached', timeout: 60000 });
  await page.waitForTimeout(1800);
  await page.screenshot({ path: `${directory}/ready.png` });
  const frame = await page.evaluate(() => window.__gardenQA.snapshot().frames);
  await page.waitForTimeout(700);
  assert.equal(await page.evaluate(() => window.__gardenQA.snapshot().frames), frame, 'loader must not keep rendering alive');
  await page.reload();
  await page.locator('.scene-loading-cover.is-revealed').waitFor({ state: 'attached', timeout: 60000 });
  await page.getByRole('button', { name: 'Use lighter rendering' }).click();
  await page.waitForTimeout(500);
  await page.locator('.scene-loading-cover.is-revealed').waitFor({ state: 'attached', timeout: 60000 });
  assert.deepEqual(errors, []);
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto(`${base}/?view=plants`);
  await page.locator('.plants-board, .plants-view').first().waitFor().catch(() => {});
  await page.screenshot({ path: `${directory}/mobile-plants.png` });
  const escape = await browser.newPage({ viewport: { width: 390, height: 844 }, reducedMotion: 'reduce' });
  let unblock;
  const blocked = new Promise(resolve => { unblock = resolve; });
  await escape.route(/\.(glb|jpe?g|png|webp)(\?.*)?$/, async route => { await blocked; await route.continue().catch(() => {}); });
  await escape.goto(`${base}/?view=model`, { waitUntil: 'domcontentloaded' });
  await escape.getByRole('button', { name: 'Explore the 2D plan' }).waitFor({ timeout: 60000 });
  await escape.screenshot({ path: `${directory}/mobile-loading.png` });
  await escape.getByRole('button', { name: 'Explore the 2D plan' }).click();
  await escape.getByRole('heading', { name: 'The measured plan', exact: true }).waitFor();
  unblock();
  await escape.close();
  console.log('Initial loading, cached revisit, reduced motion, idle rendering: passed');
} finally { await browser.close(); }
